function F = force_mag_Kdiscrete(msize1,msize2,distance,J,N)
%function F = force_mag_d(misze,distance,J)
%%Note this gives you the force on magnet2
%%Compute the magnetic force between two magnets with separation
%distance x,y,z,the dimensions of the cubes are a1,b1,c1 and a2,b2,c2
%respectively, They are set up such that a - x , b - y, c - z
%The magnets are polarized in the z direction so care must be
%taken at arbitrary polarization directions with magnitude J
%%msize = [2*a1;2*b1;2*c1];
%distance = [x,y,z] - separation distance between magnets

%%unwrap states
Jprime = J;
a = msize1(1)/2;
b = msize1(2)/2;
c = msize1(3)/2;
A = msize2(1)/2;
B = msize2(2)/2;
C = msize2(3)/2;
alfa = distance(1);
beta = distance(2);
gamma = distance(3); %%distance from center of magnets

F = [0;0;0];

u = linspace(-A,A,N(1));
v = linspace(-B,B,N(2));
w = linspace(-C,C,N(3));
du = u(2)-u(1);
dv = v(2)-v(1);
dw = w(2)-w(1);

%%Sum dF over entire volume of magnet2
for ww = 1:length(w)
  for vv = 1:length(v)
    for uu = 1:length(u)
      %disp(uu+(ww-1)*((length(v)-1)*(length(u)-1))+(vv-1)*(length(u)-1))
      x = u(uu) + alfa;
      y = v(vv) + beta;
      z = w(ww) + gamma;
      %compute dF as a function of Mag field generated by magnet1
      dF = force_mag_df(msize1,[x,y,z],J);
      %%Add to F
      F = F + dF*du*dv*dw;
    end
  end
end

% Copyright - Carlos Montalvo 2015
% You may freely distribute this file but please keep my name in here
% as the original owner
