function F = force_mag_K3discrete(msize1,msize2,distance,J,N,Rmat)
%function F = force_mag_d(misze,distance,J)
%%Note this gives you the force on magnet2
%%Compute the magnetic force between two magnets with separation
%distance x,y,z,the dimensions of the cubes are a1,b1,c1 and a2,b2,c2
%respectively, They are set up such that a - x , b - y, c - z
%The magnets are polarized in the z direction so care must be
%taken at arbitrary polarization directions with magnitude J
%%msize = [2*a1;2*b1;2*c1];
%distance = [x,y,z] - separation distance between magnets

%%unwrap states
Jprime = norm(J);
a = msize1(1)/2;
b = msize1(2)/2;
c = msize1(3)/2;
A = msize2(1)/2;
B = msize2(2)/2;
C = msize2(3)/2;
alfa = -distance(1);
beta = -distance(2);
gamma = -distance(3); %%distance from center of magnets

F = [0;0;0];

x = linspace(-A,A,N);
y = linspace(-B,B,N);
z = linspace(-C,C,N);
dx = x(2)-x(1);
dy = y(2)-y(1);
dz = z(2)-z(1);

%%Sum dF over entire volume of magnet2
for xx = 1:length(z)-1
  xI = x(xx)-alfa;
  for yy = 1:length(y)-1
    yI = y(yy)-beta;
    for zz = 1:length(x)-1
      zI = z(zz)-gamma;
      %disp(uu+(ww-1)*((length(v)-1)*(length(u)-1))+(vv-1)*(length(u)-1))
      rB = Rmat'*[xI;yI;zI];
      %compute dF as a function of Mag field generated by magnet1
      dF = force_mag_df3(msize1,rB,J);
      %%Add to F
      F = F + dF*dx*dy*dz;
    end
  end
end

% Copyright - Carlos Montalvo 2015
% You may freely distribute this file but please keep my name in here
% as the original owner
